2025-06-27 21:15:23,389 - INFO - Training with config: {'dataset_name': 'tinystory', 'context_length': 256, 'batch_size': 8, 'device': 'cpu', 'vocab_size': 10000, 'context_size': 1024, 'num_layers': 4, 'd_model': 512, 'num_heads': 16, 'd_ff': 1344, 'attn_pdrop': 0.1, 'resid_pdrop': 0.1, 'init_from': 'scratch', 'total_iters': 20000, 'warmup_iters': 200, 'cosine_cycle_iters': None, 'max_learning_rate': 0.0005, 'min_learning_rate': 0, 'weight_decay': 0.001, 'wandb_logging': True, 'wandb_project': 'cs336-assignment1', 'wandb_run_name': 'tinystories-baseline', 'log_interval': 20, 'eval_interval': 200, 'eval_iters': 100, 'no_rmsnorm': False, 'parallel_layers': False, 'post_norm': False}
2025-06-27 21:15:24,116 - INFO - number of non-embeding parameters: 8.23
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/Users/charon/Documents/GitHub/CS336/basics/train.py", line 116, in <module>
    logits = model(x)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/charon/Documents/GitHub/CS336/basics/model.py", line 247, in forward
    x=layer(x)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/charon/Documents/GitHub/CS336/basics/model.py", line 192, in forward
    x=x +self.attn(self.attn_norm(x))
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/charon/Documents/GitHub/CS336/basics/model.py", line 157, in forward
    qi=einx.rearrange('query->b... 1 query 1',seq,[b]*len(b))
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/einx/traceback_util.py", line 71, in func_with_reraise
    raise e.with_traceback(tb) from None
ValueError: Expected 1 input tensors, but got 2
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/Users/charon/Documents/GitHub/CS336/basics/train.py", line 116, in <module>
    logits = model(x)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/charon/Documents/GitHub/CS336/basics/model.py", line 247, in forward
    x=layer(x)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/charon/Documents/GitHub/CS336/basics/model.py", line 192, in forward
    x=x +self.attn(self.attn_norm(x))
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/charon/Documents/GitHub/CS336/basics/model.py", line 157, in forward
    qi=einx.rearrange('query->b... 1 query 1',seq,[b]*len(b))
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/einx/traceback_util.py", line 71, in func_with_reraise
    raise e.with_traceback(tb) from None
ValueError: Expected 1 input tensors, but got 2
